"""migr3

Revision ID: 6fa538d480f6
Revises: aa58fbd33a59
Create Date: 2024-10-05 16:00:19.379007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa538d480f6'
down_revision: Union[str, None] = 'aa58fbd33a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flower', sa.Column('description', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flower', 'description')
    # ### end Alembic commands ###
