from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa58fbd33a59'
down_revision: Union[str, None] = '5f7a5daec198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flower', sa.Column('price', sa.Float(), nullable=False, server_default="10"))

    # Оновити всі існуючі записи, встановивши ціну 10
    op.execute('UPDATE flower SET price = 10')

    # Видаляємо server_default після оновлення, щоб не було значення за замовчуванням
    op.alter_column('flower', 'price', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flower', 'price')
    # ### end Alembic commands ###
